### PR TITLE
build(deps-dev): rm eslint-plugin-unicorn entirely

### PR DESCRIPTION
**Pull request by DerekNonGeneric**
<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br /><h3>Snyk has created this PR to upgrade eslint-plugin-unicorn from 46.0.0 to 47.0.0.</h3>

:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

*Warning:* This is a major version upgrade, and may be a breaking change.
- The recommended version is **2 versions** ahead of your current version.
- The recommended version was released **a month ago**, on 2023-05-06.

<details>
<summary><b>Release notes</b></summary>
<br/>
  <details>
    <summary>Package name: <b>eslint-plugin-unicorn</b></summary>
    <ul>
      <li>
        <b>47.0.0</b> - <a href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/releases/tag/v47.0.0">2023-05-06</a></br><h3>Breaking</h3>
<ul>
<li>Require Node.js 16 (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1679821724" data-permission-text="Title is private" data-url="https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2073" data-hovercard-type="pull_request" data-hovercard-url="/sindresorhus/eslint-plugin-unicorn/pull/2073/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/pull/2073">#2073</a>)  <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/sindresorhus/eslint-plugin-unicorn/commit/a3bc1203e7fdb1504a9af8db98298e33a2a6a932/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/a3bc1203e7fdb1504a9af8db98298e33a2a6a932"><tt>a3bc120</tt></a></li>
<li>Require <code>eslint@&gt;=8.38.0</code> (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1659863104" data-permission-text="Title is private" data-url="https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2066" data-hovercard-type="pull_request" data-hovercard-url="/sindresorhus/eslint-plugin-unicorn/pull/2066/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/pull/2066">#2066</a>)  <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/sindresorhus/eslint-plugin-unicorn/commit/04af765355209bfbea408acec34e53dc8e79731d/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/04af765355209bfbea408acec34e53dc8e79731d"><tt>04af765</tt></a></li>
<li>Enable <code>prefer-at</code>, <code>prefer-event-target</code>, and <code>prefer-string-replace-all</code> in recommended config (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1679821724" data-permission-text="Title is private" data-url="https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2073" data-hovercard-type="pull_request" data-hovercard-url="/sindresorhus/eslint-plugin-unicorn/pull/2073/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/pull/2073">#2073</a>)  <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/sindresorhus/eslint-plugin-unicorn/commit/a3bc1203e7fdb1504a9af8db98298e33a2a6a932/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/a3bc1203e7fdb1504a9af8db98298e33a2a6a932"><tt>a3bc120</tt></a></li>
</ul>
<h3>New rules</h3>
<ul>
<li><a href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-blob-reading-methods.md"><code>prefer-blob-reading-methods</code></a> (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1659214822" data-permission-text="Title is private" data-url="https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2065" data-hovercard-type="pull_request" data-hovercard-url="/sindresorhus/eslint-plugin-unicorn/pull/2065/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/pull/2065">#2065</a>)  <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/sindresorhus/eslint-plugin-unicorn/commit/2bb1a04ec5376064875f0c075a8e1cf9c54c9cf5/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/2bb1a04ec5376064875f0c075a8e1cf9c54c9cf5"><tt>2bb1a04</tt></a></li>
</ul>
<h3>Improvements</h3>
<ul>
<li><code>prefer-top-level-await</code>: Ignore <code>.cjs</code> files (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1679818066" data-permission-text="Title is private" data-url="https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2072" data-hovercard-type="pull_request" data-hovercard-url="/sindresorhus/eslint-plugin-unicorn/pull/2072/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/pull/2072">#2072</a>)  <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/sindresorhus/eslint-plugin-unicorn/commit/0c3ccb11846c6f1ef8d9ee8ccf34f86c40d843d0/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/0c3ccb11846c6f1ef8d9ee8ccf34f86c40d843d0"><tt>0c3ccb1</tt></a></li>
<li><code>prefer-spread</code>: Stop checking <code>Array.from</code> call with map function (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1658818693" data-permission-text="Title is private" data-url="https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2064" data-hovercard-type="pull_request" data-hovercard-url="/sindresorhus/eslint-plugin-unicorn/pull/2064/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/pull/2064">#2064</a>)  <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/sindresorhus/eslint-plugin-unicorn/commit/f5beccb7cd4bd9edcc57ef0e1dc42d220a272a1b/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/f5beccb7cd4bd9edcc57ef0e1dc42d220a272a1b"><tt>f5beccb</tt></a></li>
<li><code>prefer-dom-node-text-content</code>: Check optional chaining (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1658795602" data-permission-text="Title is private" data-url="https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2062" data-hovercard-type="pull_request" data-hovercard-url="/sindresorhus/eslint-plugin-unicorn/pull/2062/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/pull/2062">#2062</a>)  <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/sindresorhus/eslint-plugin-unicorn/commit/8d6d007034f3f994300cb36b5c13a4101323d80a/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/8d6d007034f3f994300cb36b5c13a4101323d80a"><tt>8d6d007</tt></a></li>
<li><code>prefer-dom-node-{append,remove}</code>: Check optional chaining (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1658785579" data-permission-text="Title is private" data-url="https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2061" data-hovercard-type="pull_request" data-hovercard-url="/sindresorhus/eslint-plugin-unicorn/pull/2061/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/pull/2061">#2061</a>)  <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/sindresorhus/eslint-plugin-unicorn/commit/443999b63e30263f8a6230363bf3455c904b3ae2/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/443999b63e30263f8a6230363bf3455c904b3ae2"><tt>443999b</tt></a></li>
</ul>
<h3>Fixes</h3>
<ul>
<li><code>prefer-number-properties</code>: Fix false positives (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1618640396" data-permission-text="Title is private" data-url="https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2050" data-hovercard-type="pull_request" data-hovercard-url="/sindresorhus/eslint-plugin-unicorn/pull/2050/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/pull/2050">#2050</a>)  <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/sindresorhus/eslint-plugin-unicorn/commit/124bfa74e91ba9825b773f61baeacdffc6ec5f1a/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/124bfa74e91ba9825b773f61baeacdffc6ec5f1a"><tt>124bfa7</tt></a></li>
</ul>
<p><a class="commit-link" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/compare/v46.0.0...v47.0.0"><tt>v46.0.0...v47.0.0</tt></a></p>
      </li>
      <li>
        <b>46.0.1</b> - <a href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/releases/tag/v46.0.1">2023-05-06</a></br><ul>
<li>Fix <code>expiring-todo-comments</code> (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1698368611" data-permission-text="Title is private" data-url="https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2077" data-hovercard-type="pull_request" data-hovercard-url="/sindresorhus/eslint-plugin-unicorn/pull/2077/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/pull/2077">#2077</a>)  <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/sindresorhus/eslint-plugin-unicorn/commit/7a6861a529b6e75ce98efe14d4b1b377c886e91e/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/7a6861a529b6e75ce98efe14d4b1b377c886e91e"><tt>7a6861a</tt></a></li>
</ul>
<p><a class="commit-link" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/compare/v46.0.0...v46.0.1"><tt>v46.0.0...v46.0.1</tt></a></p>
      </li>
      <li>
        <b>46.0.0</b> - <a href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/releases/tag/v46.0.0">2023-03-03</a></br><h3>Improvements</h3>
<ul>
<li>Add <code>elems</code> to abbreviations (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1570401403" data-permission-text="Title is private" data-url="https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2040" data-hovercard-type="pull_request" data-hovercard-url="/sindresorhus/eslint-plugin-unicorn/pull/2040/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/pull/2040">#2040</a>)  <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/sindresorhus/eslint-plugin-unicorn/commit/2a9c840484ab456ef131cb7ffc61cd46bef443a7/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/2a9c840484ab456ef131cb7ffc61cd46bef443a7"><tt>2a9c840</tt></a></li>
<li><code>no-useless-spread</code>: Check <code>Array#{toReversed,toSorted,toSpliced,with}</code> (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1565898333" data-permission-text="Title is private" data-url="https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2030" data-hovercard-type="pull_request" data-hovercard-url="/sindresorhus/eslint-plugin-unicorn/pull/2030/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/pull/2030">#2030</a>)  <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/sindresorhus/eslint-plugin-unicorn/commit/55469e5b70b4d62584f5f47623c4dbdbd7f9eebe/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/55469e5b70b4d62584f5f47623c4dbdbd7f9eebe"><tt>55469e5</tt></a></li>
<li><code>prefer-set-has</code>: Support <code>Array#{toReversed,toSorted,toSpliced,with}</code> (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1565959944" data-permission-text="Title is private" data-url="https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2032" data-hovercard-type="pull_request" data-hovercard-url="/sindresorhus/eslint-plugin-unicorn/pull/2032/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/pull/2032">#2032</a>)  <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/sindresorhus/eslint-plugin-unicorn/commit/fea5b42d5bcc5397b0ddfc525307377a6494a16f/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/fea5b42d5bcc5397b0ddfc525307377a6494a16f"><tt>fea5b42</tt></a></li>
<li><code>prefer-spread</code>: Forbid use of <code>Array#toSpliced()</code> to copy array (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1566101134" data-permission-text="Title is private" data-url="https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2034" data-hovercard-type="pull_request" data-hovercard-url="/sindresorhus/eslint-plugin-unicorn/pull/2034/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/pull/2034">#2034</a>)  <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/sindresorhus/eslint-plugin-unicorn/commit/4ada50e896dca899b029ada6a55ebf2141252251/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/4ada50e896dca899b029ada6a55ebf2141252251"><tt>4ada50e</tt></a></li>
<li><code>prefer-negative-index</code>: Check <code>.toSpliced()</code> and <code>.with()</code> (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1565949706" data-permission-text="Title is private" data-url="https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2031" data-hovercard-type="pull_request" data-hovercard-url="/sindresorhus/eslint-plugin-unicorn/pull/2031/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/pull/2031">#2031</a>)  <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/sindresorhus/eslint-plugin-unicorn/commit/7ed738a41d5f611b1907dc2a9afd2c454300577a/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/7ed738a41d5f611b1907dc2a9afd2c454300577a"><tt>7ed738a</tt></a></li>
<li><code>no-empty-file</code>: Support <code>.jsx</code> and <code>.tsx</code> extensions (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1469593790" data-permission-text="Title is private" data-url="https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2002" data-hovercard-type="pull_request" data-hovercard-url="/sindresorhus/eslint-plugin-unicorn/pull/2002/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/pull/2002">#2002</a>)  <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/sindresorhus/eslint-plugin-unicorn/commit/ba1a00ee1a9bf90ca284e241cd8f137216c2f2aa/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/ba1a00ee1a9bf90ca284e241cd8f137216c2f2aa"><tt>ba1a00e</tt></a></li>
</ul>
<h3>Fixes</h3>
<ul>
<li><code>expiring-todo-comments</code>: Do not normalize package.json (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1321304670" data-permission-text="Title is private" data-url="https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1871" data-hovercard-type="issue" data-hovercard-url="/sindresorhus/eslint-plugin-unicorn/issues/1871/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/issues/1871">#1871</a>) (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1507682005" data-permission-text="Title is private" data-url="https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2020" data-hovercard-type="pull_request" data-hovercard-url="/sindresorhus/eslint-plugin-unicorn/pull/2020/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/pull/2020">#2020</a>)  <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/sindresorhus/eslint-plugin-unicorn/commit/fcd893465f8e3cc59d34d6d1db533cea94247a0c/hovercard" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/fcd893465f8e3cc59d34d6d1db533cea94247a0c"><tt>fcd8934</tt></a></li>
</ul>
<p><a class="commit-link" href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/compare/v45.0.2...v46.0.0"><tt>v45.0.2...v46.0.0</tt></a></p>
      </li>
    </ul>
    from <a href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/releases">eslint-plugin-unicorn GitHub release notes</a>
  </details>
</details>

<details>
  <summary><b>Commit messages</b></summary>
  </br>
  <details>
    <summary>Package name: <b>eslint-plugin-unicorn</b></summary>
    <ul>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/6f05ddc6f4b350029c4597ed51d4cc445cc958d3">6f05ddc</a> 47.0.0</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/6ee3687da6b334118cda627401153c3c13e20e70">6ee3687</a> Fix &#x60;expiring-todo-comments&#x60; (#2077)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/0c3ccb11846c6f1ef8d9ee8ccf34f86c40d843d0">0c3ccb1</a> &#x60;prefer-top-level-await&#x60;: Ignore &#x60;.cjs&#x60; files (#2072)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/a3bc1203e7fdb1504a9af8db98298e33a2a6a932">a3bc120</a> Require Node.js 16, enable &#x60;prefer-at&#x60;, &#x60;prefer-event-target&#x60;, and &#x60;prefer-string-replace-all&#x60; in recommended config (#2073)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/a9337e847e0ca4d725bdedf8f13e24c7d0dfcda9">a9337e8</a> Extend explanations for some rules (#2070)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/2bb1a04ec5376064875f0c075a8e1cf9c54c9cf5">2bb1a04</a> Add &#x60;prefer-blob-reading-methods&#x60; rule (#2065)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/d90f3379f00050320951b07e50754467fb853719">d90f337</a> Use &#x60;SourceCode#getScope&#x60; (#2068)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/f14433068bbf92d56b3aaa457c5a1aa0ec19e7ab">f144330</a> Meta tweaks</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/1eca7d072dd42940dcfda0a022edec452f79c105">1eca7d0</a> Switch to MDN links (#2069)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/04af765355209bfbea408acec34e53dc8e79731d">04af765</a> Use &#x60;SourceCode#{getDeclaredVariables,getAncestors}&#x60;, require &#x60;eslint@&gt;&#x3D;8.38.0&#x60; (#2066)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/f5beccb7cd4bd9edcc57ef0e1dc42d220a272a1b">f5beccb</a> &#x60;prefer-spread&#x60;: Stop checking &#x60;Array.from&#x60; call with map function (#2064)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/8d6d007034f3f994300cb36b5c13a4101323d80a">8d6d007</a> &#x60;prefer-dom-node-text-content&#x60;: Check optional chaining (#2062)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/443999b63e30263f8a6230363bf3455c904b3ae2">443999b</a> &#x60;prefer-dom-node-{append,remove}&#x60;: Check optional chaining (#2061)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/0f4f4927c2ff53a507a73e584e8e8abf44057888">0f4f492</a> Update dependencies (#2060)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/124bfa74e91ba9825b773f61baeacdffc6ec5f1a">124bfa7</a> &#x60;prefer-number-properties&#x60;: Fix false positives (#2050)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/commit/e1c50ac39874f69d20a661d8df8f003aa186a393">e1c50ac</a> Fix broken link</li>
    </ul>

   <a href="https://snyk.io/redirect/github/sindresorhus/eslint-plugin-unicorn/compare/5fcdf0f3f1e74b4c8a92853ecc75fd7721463145...6f05ddc6f4b350029c4597ed51d4cc445cc958d3">Compare</a>
  </details>
</details>
<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  

🧐 [View latest project report](https://app.snyk.io/org/openinf/project/f770a775-4ad3-480b-bb22-6c4c051fd318?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/openinf/project/f770a775-4ad3-480b-bb22-6c4c051fd318/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/openinf/project/f770a775-4ad3-480b-bb22-6c4c051fd318/settings/integration?pkg&#x3D;eslint-plugin-unicorn&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Comment by DerekNonGeneric** [comment]
> Warning: This is a major version upgrade, and may be a breaking change.
>
>    The recommended version is 2 versions ahead of your current version.
>    The recommended version was released a month ago, on 2023-05-06.

@lirantal using my credentials for this is abusive (PRs are permanent); please look into it.

**Comment by DerekNonGeneric** [comment]
So why did we add this dependency in the first place? Simply for helping to migrate towards [prevent-abbreviations](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/HEAD/docs/rules/prevent-abbreviations.md), and probably some other things, but mainly that.

Socket score not looking good tho.

**Comment by DerekNonGeneric** [comment]
> [&hellip;] and probably some other things, but mainly that.

For posterity's take, all of this config is still located [here](https://github.com/OpenINF/openinf-util-object/blob/78ee584a986aba5fdb0362a50b0a8dc8b56f5e2e/.eslintrc.cjs#LL58C5-L72C9). This would all be getting folded into OpenINF's Style Guide Standards tho.

**Comment by lirantal** [comment]
>>  Warning: This is a major version upgrade, and may be a breaking change.

>> The recommended version is 2 versions ahead of your current version.
>> The recommended version was released a month ago, on 2023-05-06.

> @lirantal using my credentials for this is abusive (PRs are permanent); please look into it.

@DerekNonGeneric I can only assume that you have at one point connected to Snyk with your GitHub account and added this repository to monitor which it then automated PR security fixes and package updates. Can you login to Snyk and confirm? there you can also choose to remove this repository from receiving such updates

**Comment by DerekNonGeneric** [comment]
Hi Liran, sorry about the delayed response. Can you confirm the below is how it should look?

image

**Pull request merged**
